<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Measurement" Id="{d5e65a98-c59a-40a4-8e08-14b2a0104701}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Measurement IMPLEMENTS IOut
VAR_INPUT
    value : LREAL;
END_VAR
VAR
    _out : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_out := value;
]]></ST>
    </Implementation>
    <Method Name="Derivative" Id="{3cb626dd-f306-4dd7-8b41-c5d14146e141}">
      <Declaration><![CDATA[METHOD Derivative : REFERENCE TO Measurement
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Out" Id="{f11c0c9d-cbae-4516-9e11-e42329123126}">
      <Declaration><![CDATA[PROPERTY Out : LREAL
]]></Declaration>
      <Get Name="Get" Id="{42b506ae-6bce-45b3-bdd7-aeb51ebf09f3}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[OUT := _out;
]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>